name: Build and deploy

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: auto
      GOPRIVATE: github.com/BOOMfinity-Developers/*
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Switch git to SSH
        run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"

      - name: Setup SSH Keys and known_hosts
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GH_SSH_PRIVATE_KEY }}"


      - name: Build
        run: go build -ldflags="-X 'goprodukcji/events.GitCommitHash=${GITHUB_SHA}'"

      - name: Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SSH_IP }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          scp_source: goprodukcji
          scp_target: ~/goprodukcji/
          before_script: sudo systemctl stop goprodukcji.service
          after_script: sudo systemctl start goprodukcji.service