name: Build & SSH Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: auto
      GOPRIVATE: github.com/BOOMfinity-Developers/*
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

      
    - name: Build
      run: go build .


    - name: Deploy
      uses: marcodallasanta/ssh-scp-deploy@v1.0.4
      with:
        local: ./NaProdukcjiGoSender
        host: ${{secrets.SSH_IP}}
        user: ${{secrets.SSH_USER}}
        password: ${{secrets.SSH_PASSWORD}}
        pre_upload: whoami
        post_upload: ./NaProdukcjiGoSender ${{secrets.DISCORD_TOKEN}}

