name: Build & SSH Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: auto
      GOPRIVATE: github.com/BOOMfinity-Developers/*
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Fix Git
        run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GH_SSH_PRIVATE_KEY }}"


      - name: Build
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: go build .

      - name: LS
        run: ls

      - name: Deploy
        uses: marcodallasanta/ssh-scp-deploy@v1.0.4
        with:
          local: gosender
          host: ${{secrets.SSH_IP}}
          user: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          #post_upload: ./NaProdukcjiGoSender ${{secrets.DISCORD_TOKEN}}