name: SSH Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build .

    - name: Deploy
      uses: marcodallasanta/ssh-scp-deploy@v1.0.4
      with:
        local: ./NaProdukcjiGoSender
        host: ${{SSH_IP}}
        user: ${{SSH_USER}}
        password: ${{SSH_PASSWORD}}
        pre_upload: whoami
        post_upload: ./NaProdukcjiGoSender ${{DISCORD_TOKEN}}

